version: '3.8'
services:
  bot:
      build: 
        context: .
      restart: 
        on-failure
      environment:
        ADMIN: ${ADMIN}
        BOTTOKEN: ${BOTTOKEN}
        DBURL: ${DBURL-bot.db}
        RUNTYPE: ${RUNTYPE-polling}
        DOMEN: ${DOMEN-127.0.0.1}
        HOST: ${HOST-localhost}
        PORT: ${PORT-8080}
        TZ: Europe/Moscow
      depends_on:
        - certbot
  
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt/:/etc/certs/
      - /var/www/html/:/var/www/html/
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMEN} --staging