version: '3.8'
services:
  bot:
      build: 
        context: .
      restart: 
        on-failure
      environment:
        ADMIN: ${ADMIN}
        BOTTOKEN: ${BOTTOKEN}
        DBURL: ${DBURL-bot.db}
        RUNTYPE: wehook
        DOMEN: ${DOMEN-127.0.0.1}
        HOST: ${HOST-localhost}
        PORT: ${PORT-8080}
        TZ: Europe/Moscow

  nginx:
    image: nginx:1.25.2-alpine-slim
    restart: unless-stoped
    links:
      - bot
    ports:
      - 80:80
      - 443:443
    volumes:
      - www-html:/var/www/html:ro
      - etc-letsencrypt:/etc/letsencrypt:ro
      - ./nginx-conf.d/:/etc/nginx/conf.d:ro
  
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt/:/etc/certs/
      - /var/www/html/:/var/www/html/
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMEN}

volumes:
  etc-letsencrypt:
  www-html: